# Generated by Django 5.2.1 on 2025-07-17 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location_type', models.CharField(choices=[('STORAGE', 'مخزن'), ('DISTRIBUTION', 'موقع توزيع'), ('OFFICE', 'مكتب'), ('HALL', 'قاعة'), ('OTHER', 'آخر')], default='STORAGE', max_length=20, verbose_name='نوع الموقع')),
            ],
            options={
                'verbose_name': 'موقع',
                'verbose_name_plural': 'المواقع',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'وحدة',
                'verbose_name_plural': 'الوحدات',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العنصر')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almukhzan.category', verbose_name='الفئة')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almukhzan.storagelocation', verbose_name='الموقع')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almukhzan.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'الاصل',
                'verbose_name_plural': 'الاصول',
            },
        ),
        migrations.CreateModel(
            name='ItemActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('performed_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almukhzan.inventoryitem')),
            ],
            options={
                'verbose_name': 'سجل إجراء',
                'verbose_name_plural': 'سجلات الإجراءات',
            },
        ),
        migrations.CreateModel(
            name='ItemMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'إدخال'), ('OUT', 'إخراج'), ('ADJUST', 'تعديل')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almukhzan.inventoryitem')),
            ],
            options={
                'verbose_name': 'نقل أصل',
                'verbose_name_plural': 'مناقلات أصول',
            },
        ),
    ]
