# Generated by Django 5.2.1 on 2025-08-19 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almukhzan', '0002_employee_inventoryitem_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='almukhzan.unit', verbose_name='الوحدة الادارية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='almukhzan.unit'),
        ),
    ]
