# Generated by Django 5.2.1 on 2025-07-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almukhzan', '0002_alter_inventoryitem_options_inventoryitem_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': 'الاصل', 'verbose_name_plural': 'الاصول'},
        ),
        migrations.AlterModelOptions(
            name='itemactionlog',
            options={'verbose_name': 'سجل إجراء', 'verbose_name_plural': 'سجلات الإجراءات'},
        ),
        migrations.AlterModelOptions(
            name='itemmovement',
            options={'verbose_name': 'نقل أصل', 'verbose_name_plural': 'مناقلات أصول'},
        ),
        migrations.AlterModelOptions(
            name='storagelocation',
            options={'verbose_name': 'موقع', 'verbose_name_plural': 'المواقع'},
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='location_type',
            field=models.CharField(choices=[('STORAGE', 'مخزن'), ('DISTRIBUTION', 'موقع توزيع'), ('OFFICE', 'مكتب'), ('OTHER', 'آخر')], default='STORAGE', max_length=20, verbose_name='نوع الموقع'),
        ),
    ]
