# Generated by Django 5.2.1 on 2025-08-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almukhzan', '0003_storagelocation_unit_alter_employee_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='unit',
        ),
    ]
