# Generated by Django 5.2.1 on 2025-07-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almukhzan', '0003_alter_inventoryitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagelocation',
            name='location_type',
            field=models.CharField(choices=[('STORAGE', 'مخزن'), ('DISTRIBUTION', 'موقع توزيع'), ('OFFICE', 'مكتب'), ('HALL', 'قاعة'), ('OTHER', 'آخر')], default='STORAGE', max_length=20, verbose_name='نوع الموقع'),
        ),
    ]
